- name: installing nginx
  hosts: web
  become: yes

  tasks:
  - name: Install nginx
    ansible.builtin.dnf:
        name: nginx
        state: installed

  - name: start nginx if not started      
    ansible.builtin.service:
        name: nginx
        state: started
        enabled: yes

